# Generated by Django 5.1.2 on 2024-10-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["created_at"]},
        ),
    ]
